spring.application.name=gymApp

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/gym_app
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true

# Security logging
logging.level.org.springframework.security=DEBUG

# JWT
jwt.secret=NjM0Njg2YzQyNTM0OTUwNTY0NTQ2Nzc4OTBhYmNkZWY=
jwt.expiration=86400000